Added Github MarketPlace Cards Box-shadow
nakulrathore/Box-Shadows pull request #175
Opened 2020-10-05 12:41 UTC by HooriaHIC

2020-10-05 12:45 UTC, HooriaHIC commented
#175

2020-10-05 12:46 UTC, HooriaHIC commented
#45

2020-10-06 07:50 UTC, nakulrathore commented on src/shadows.js
>    }
add a comma ending last item of the array.

2020-10-06 07:51 UTC, nakulrathore requested changes
update the file with requested comment.

2020-10-06 09:36 UTC, closed without merging

2020-10-06 09:36 UTC, HooriaHIC commented
I've Submited another pull request with the changes you requested :)